language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1           # automatically the latest version to this major
  - 1.0         # set manually to the version given in REQUIRE
  - nightly
git:
  depth: 3
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
